virtio: use 2k19 virtio drivers
cloudbase/windows-openstack-imaging-tools pull request #350
Opened 2020-11-16 11:17 UTC by ader1990

Use Windows build numbers to map the Fedora VirtIO drivers to be
installed.

Build number intervals for each Windows version in CSV format:

Windows Version, Minimum Build, Maximum Build, IsServerVersion

"2k8", 6000, 6003, true
"2k8r2", 7600, 8400, true
"w7", 7600, 8400, false
"2k12", 9200, 9200, true
"w8", 9200, 9200, false)
"2k12r2", 9600, 9900, true
"w8.1", 9600, 9900, false
"2k16", 14393, 16299, true
"w10", 10240, 999999, false
"2k19", 17763, 999999, true

2020-11-16 11:20 UTC, ader1990 commented
@felfert @mikeycarlton @zpeschke, I would appreciate a review for this PR.

Thank you,
Adrian Vladu

2020-11-16 13:01 UTC, felfert requested changes

2020-11-16 13:09 UTC, ader1990 commented on WinImageBuilder.psm1
> +            "BuildNumber" = $osVersion[1];
updated, thanks.

2021-02-02 07:12 UTC, andreitira commented
Tested the PR and everything is working smoothly.

2021-02-02 07:13 UTC, andreitira approved these changes
lgtm

2021-02-02 08:47 UTC, merged